# render.yaml
previews:
  generation: automatic

services:
  - type: web
    name: mallos-api
    runtime: docker
    ...
  - type: web
    name: mallos-dashboard
    runtime: static
    plan: starter
    rootDir: frontend
    buildCommand: yarn install && yarn build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://mallos-api.onrender.com
