name: Generate lockfiles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate root lockfile
        run: npm install
      - name: Generate frontend lockfile
        run: |
          cd frontend
          npm install
      - name: Commit lockfiles
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json frontend/package-lock.json
          git commit -m "Generate package-lock.json files via GitHub Actions" || echo "No changes to commit"
          git push
