name: Generate lockfiles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean root lockfile and node_modules
        run: |
          rm -rf node_modules package-lock.json
      - name: Generate root lockfile
        run: npm install --legacy-peer-deps
      - name: Commit lockfiles
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "Generate package-lock.json files via GitHub Actions" || echo "No changes to commit"
          git push
